### ISSUE TITLE
帖子显示页面对列表显示不正确

### ISSUE THREAD

**Issue by huobazi** [hanji1122/RubyChina#2]
比如这个帖子的8楼 https://ruby-china.org/topics/29508#reply8 中的内容在帖子页面显示是堆积起来的，该回复详情页面显示是正确的。

**Comment by hanji1122** [comment]
回复内容为 html 格式，在帖子详情页中，因为性能问题回复评论没有使用 WebView 渲染，采用富文本方式显示，限制为最多显示6行，超出6行末尾显示省略号。回复详情页使用 WebView 渲染回复的全部内容。
